from django.conf.urls import url
from app import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.Login.as_view(), name='login'),
    url(r'^home/$', views.home, name='home'),
    url(r'^stock/$', views.stock, name='stock'),
    url(r'^stats/$', views.stats, name='stats'),
    url(r'^test/$', views.test, name='test'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^ajax/like/$', views.like, name='like'),
    url(r'^ajax/check_in/$', views.check_in, name='check_in'),
    url(r'^ajax/delete_product/$', views.delete_product, name='del_p'),
    url(r'^ajax/delete_account/$', views.delete_account, name='del_a'),
    # url(r'^loginReq/',views.loginReq, name = 'loginReq'),
    # url(r'^gestionproductos/$', views.gestionproductos,name='gestionproductos'),
    # url(r'^vendedorprofilepage/$', views.vendedorprofilepage,name='vendedorprofilepage'),
    # url(r'^formView/', views.formView, name='formView'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^edit_account$', views.EditAccount.as_view(), name='edit_account'),
    url(r'^edit_product/(?P<pid>[0-9]+)/$', views.EditProduct.as_view(), name='edit_products'),
    url(r'^vendor/(?P<pid>[0-9]+)/$', views.vendor_info, name='vendor_info'),
    # url(r'^register/', views.register, name='register'),
    # url(r'^loggedin/', views.loggedin, name='loggedin'),
    # url(r'^productoReq/', views.productoReq, name='productoReq'),
    # url(r'^vistaVendedorPorAlumno/', views.vistaVendedorPorAlumno, name='vistaVendedorPorAlumno'),
    # url(r'^cambiarEstado/$', views.cambiarEstado,name='cambiarEstado'),
    # url(r'^editarVendedor/$', views.editarVendedor,name='editarVendedor'),
    # url(r'^editarDatos/$', views.editarDatos,name='editarDatos'),
    # url(r'^inicioAlumno/', views.inicioAlumno, name='inicioAlumno'),
    # url(r'^borrarUsuario/', views.borrarUsuario, name='borrarUsuario'),
    # url(r'^borrarProducto/', views.borrarProducto, name='borrarProducto'),
    # url(r'^editarProducto/', views.editarProducto, name='editarProducto'),
    # url(r'^cambiarFavorito/', views.cambiarFavorito, name='cambiarFavorito'),
    # url(r'^vistaVendedorPorAlumnoSinLogin/', views.vistaVendedorPorAlumnoSinLogin,
    #  name='vistaVendedorPorAlumnoSinLogin'),
    # url(r'^editarPerfilAlumno/', views.editarPerfilAlumno,name='editarPerfilAlumno'),
    # url(r'^procesarPerfilAlumno/', views.procesarPerfilAlumno,name='procesarPerfilAlumno'),
    # url(r'^editarUsuario/', views.editarUsuario, name='editarUsuario'),
    # url(r'^agregarAvatar/', views.agregarAvatar, name='agregarAvatar'),
    # url(r'^signupAdmin/$', views.signupAdmin,name='signupAdmin'),
    # url(r'^registerAdmin/$', views.registerAdmin,name='registerAdmin'),
    # url(r'^getStock/$', views.getStock,name='getStock'),
    # url(r'^verificarEmail/$', views.verificarEmail,name='verificarEmail'),
    # url(r'^adminEdit/$', views.adminEdit,name='adminEdit'),
    # url(r'^editarUsuarioAdmin/$', views.editarUsuarioAdmin,name='editarUsuarioAdmin'),
    # url(r'^loginAdmin/$', views.loginAdmin, name='loginAdmin'),
    # url(r'^createTransaction/$', views.createTransaction, name='createTransaction'),
    # url(r'^fijoDashboard/$', views.fijoDashboard, name='fijoDashboard'),
    # url(r'^ambulanteDashboard/$', views.ambulanteDashboard, name='ambulanteDashboard'),

]
